os:
- linux
- osx
dist: xenial

addons:
  apt:
    packages:
      - g++
      - cmake
      - libjsoncpp-dev
    update: true
  homebrew:
    packages:
      - jsoncpp
    update: true

language: python
python:
- "3.5"
- "3.6"
- "3.7"

install:
- make venv
script:
- make test
