dist: xenial
os: osx
language: python
addons:
  apt:
    packages:
      - g++
      - cmake
      - libjsoncpp-dev
    update: true
  homebrew:
    packages:
      - jsoncpp
    update: true
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - make venv
script:
  - make test
